version: '3.8'

services:
  encriptacion-api:
    image: marcosjpa22/encriptacion-api-cp
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  encriptacion-web:
    image: marcosjpa22/encriptacion-web-cp
    ports:
      - "80:80"
    depends_on:
      - encriptacion-api